### PR TITLE
tbl_graph method for clean_names

### PR DESCRIPTION
**Pull request by JosiahParry**
Addressing issue https://github.com/sfirke/janitor/issues/252. 
Creating a method for `tbl_graph` objects.

### CODE REVIEW

**Comment by JosiahParry** [comment]
Not sure why old commits are being shown as new in the PR. If you have any resources for preventing this, please let me know.

**Comment by sfirke** [comment]
I'll take a closer look from a computer but you could try making a new
branch from the latest commit of sfirke/janitor master. Or possibly saving
your new commits somewhere, resetting the head of your current branch to
the end of the previous commits, pulling from sfirke/janitor, and redoing
the commits.

Thanks for taking on this one too!

**Comment by sfirke** [comment]
can you add tidygraph pkg to "Suggests" in the DESCRIPTION file and add a blurb to NEWS.md, where it currently says clean_names() now works on `sf` objects?

**Comment by JosiahParry** [comment]
Yes I can! Right now my computer is getting repaired so I’ll try and do
this over the weekend.

Thanks!

**Comment by JosiahParry** [comment]
`DESCRIPTION` and news have been updated.

**Comment by sfirke** [comment]
Looks good, thank you, and I see it is passing checks now.  Two more items:
- Add a check for the tidygraph package being installed, like this for clean_names.sf - you can almost copy verbatim: https://github.com/sfirke/janitor/blob/4bf8ddfc9b1bb1bd43e794431db021bf0010cba0/R/clean_names.R#L72-L75
- Update documentation for `clean_names` to note that it works on `sf` and `tidygraph` objects.  I think most of the language should remain as is, focused on data.frames, but it would be good to mention "data.frame or other object" up front and then in the description note "clean_names also works on objects of class sf and tidygraph"

Would you be up for those?  Then I think this can be merged.

**Comment by JosiahParry** [comment]
Absolutely. 

One thing to think about is if you want the `clean_names()` function to work on named lists and named vectors. Currently the default method would be able to handle named lists and named vectors except for the `!is.data.frame(dat)` check.

**Pull request merged**
