### PR TITLE
Translate extended ASCII to printable ASCII in make_clean_names()

### LINKED ISSUE #389: Superscript two in make_clean_names
Hi.

`janitor::make_clean_names()` doesn't clean a superscript 2 (aka exponent 2, square,...) : "²". I expected (maybe wrongly) that 
`janitor::make_clean_names("m²")` would return "m2" :
```r
    make_clean_names("m²")
    # [1] "m²"

    iconv("m²", "Windows-1252", "ASCII//TRANSLIT")
    # [1] "m2"
    
    iconv("m²", "UTF-8", "ASCII//TRANSLIT")
    # [1] NA
    
    charToRaw("m²")
    # [1] 6d b2
    
    stringi::stri_trans_general("m²", "Any-Latin")
    # [1] "m²"
```

This character is not fully valid if used in a column name in a database like PostgreSQL (i.e. the column will have to be accessed with quotes in queries), so it can raise problems.

Thanks

```
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
[3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] janitor_2.0.1 shiny_1.4.0.2

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.0  xfun_0.15         remotes_2.1.1     purrr_0.3.4       snakecase_0.11.0 
 [6] vctrs_0.3.1       generics_0.0.2    testthat_2.3.2    miniUI_0.1.1.1    htmltools_0.5.0  
[11] usethis_1.6.1     rlang_0.4.6       pkgbuild_1.0.8    pillar_1.4.4      later_1.1.0.1    
[16] glue_1.4.1        withr_2.2.0       sessioninfo_1.1.1 lifecycle_0.2.0   stringr_1.4.0    
[21] devtools_2.3.0    memoise_1.1.0     evaluate_0.14     knitr_1.29        callr_3.4.3      
[26] fastmap_1.0.1     httpuv_1.5.4      ps_1.3.3          fansi_0.4.1       Rcpp_1.0.4.6     
[31] xtable_1.8-4      clipr_0.7.0       promises_1.1.1    backports_1.1.7   desc_1.2.0       
[36] pkgload_1.1.0     jsonlite_1.6.1    mime_0.9          fs_1.4.1          packrat_0.5.0    
[41] digest_0.6.25     stringi_1.4.6     processx_3.4.2    dplyr_1.0.0       rprojroot_1.3-2  
[46] cli_2.0.2         tools_3.6.0       magrittr_1.5      tibble_3.0.1      pkgconfig_2.0.3  
[51] crayon_1.3.4      whisker_0.4       ellipsis_0.3.1    prettyunits_1.1.1 lubridate_1.7.9  
[56] reprex_0.3.0      assertthat_0.2.1  rmarkdown_2.3     rstudioapi_0.11   R6_2.4.1         
[61] compiler_3.6.0   
```

### PR DESCRIPTION
**Pull request by billdenney**
Fix #389

### CODE REVIEW

**Comment by billdenney** [comment]
The PR works on my local system but appears to fail on Travis.  @sfirke, can you please give it a test on your system to see if you can get it working?

**Comment by sfirke** [comment]
Weird.  The tests pass on my local system, too.  I wonder what it is about the Travis setups - all of them - that make this fall.  Here's from the failure logs:

```
> test_check("janitor")

── 1. Failure: All scenarios for make_clean_names (@test-clean-names.R#135)  ───

make_clean_names("m\x83\x84\x85\x86\x87\xa1") not equal to "mf".

1/1 mismatches

x[1]: "m"

y[1]: "mf"

extended ASCII test 1

── 2. Failure: All scenarios for make_clean_names (@test-clean-names.R#140)  ───

make_clean_names("m\xa9\xaa\xae\xb2\xb3\xb5\xbc\xbd\xbe\xc0") not equal to "m_c_a_r_23m1_41_23_4a".

1/1 mismatches

x[1]: "m"

y[1]: "m_c_a_r_23m1_41_23_4a"

extended ASCII test 2
```

**Comment by billdenney** [comment]
Perhaps "nfc", "nfd", "nfkc", and "nfkd" are not available on Travis.  (Argh!)  The issue on detecting those is awaiting response.  We may need to wait for that.

**Comment by dicorynia** [comment]
Thanks !

**Comment by billdenney** [comment]
@sfirke, using Unicode seems to fix it.  Please merge upon review.

**Comment by sfirke** [comment]
Thanks for adjusting!

**Pull request merged**
