### PR TITLE
increased tidyeval use

### PR DESCRIPTION
**Pull request by bfgray3**
* take advantage of tidyeval when possible instead of using underscore-postfixed tidyverse functions
* other small changes

### CODE REVIEW

**Comment by sfirke** [comment]
Thanks for this!  It's a wide-ranging PR so might take me some time to wade through it.  If there are parts I have questions about I'll tag you in a comment.  I'm especially interested in your rewrite of the "new" dplyr tidyeval with `!!` etc. - I'm new to that and look forward to seeing what you did there.

**Comment by bfgray3** [comment]
Thanks for your kind response.  Let me know if you have any questions at all.

**Comment by sfirke** [comment]
hi @bfgray3 - I'm finally gearing up to review this.  I think there will be some parts I'm very interested in keeping (proper tidyeval usage) and others less-so (refactoring deprecated functions) so may want to pick and choose a bit.  To that end, could you grant me commit access to `bfgray3/janitor` so I can commit to the branch?

Also, and I apologize for this, the master branch has evolved since this PR was submitted, increasing the amount of work to merge.  I think the way to proceed there would be to rebase bfgray3/janitor onto the current sfirke/janitor master branch, deal with conflicts there, so it can easily merge into the master branch at the end with checks passing.  Do you support that or see a better alternative?  And if you think that's the way to go, if you can do the rebase, that would be excellent.  You could build your changes onto the current versions of `tabyl`, etc.  Or if you can't do the rebase, then I think I could, with the aforementioned commit access.

**Comment by bfgray3** [comment]
I've just tried to give you access to my fork.  Let me know if that doesn't work for you and I'll try again.  I'll take a shot at the rebasing and get back to you in a few days.  Thanks!

**Comment by sfirke** [comment]
Yep, looks like that worked!  And thanks for taking a crack at the rebasing

**Comment by bfgray3** [comment]
I'm, not an expert at rebasing (don't know if I've ever actually done it before) and I'm afraid I've really messed this up.  I thought I'd finished and did `git push --force origin tidyeval`, which pretty much wiped out all the work.  I do have these hashes printed out from the output of the command, do you know if there's any way at all to save anything?

``
To https://github.com/bfgray3/janitor
 + cdd26e7...740b00f tidyeval -> tidyeval (forced update)
```

**Comment by bfgray3** [comment]
Sorry about this.  I've now managed to get back the pre-rebased work in my fork, but the PR has been deleted.  At this point, and given my limited git skills, it might be easiest for me to just note the important changes and make a new PR rather than salvaging the old one.  What do you think?

**Comment by sfirke** [comment]
That sounds good and I saw you just opened a new pul request.  Get vexed, salvage the actual changes, and then burn-down-and-reset the repo is a classic series of Git steps 😄

I see I can't reopen this PR b/c "the repository that submitted this pull request has been deleted", so let's go with your new one and I'll take the conversation over there.

**Pull request closed without merging**
