### PR TITLE
Add 'none' and 'internal_parsing' to make_clean_names and clean_names

### LINKED ISSUE #150: Add test for print.tabyl
To confirm it prints w/o row numbers.  See https://stackoverflow.com/q/47397008/4470365

### LINKED ISSUE #269: clean_names should support 'none' as a case option
The documentation for clean_names states:

> "parsed", "mixed", "none", "internal_parsing": less-common cases offered by snakecase::to_any_case. See to_any_case for details.

but the arguments in the function signature are 
`
function (dat, case = c("snake", "lower_camel", "upper_camel", 
    "screaming_snake", "lower_upper", "upper_lower", "all_caps", 
    "small_camel", "big_camel", "old_janitor", "parsed", "mixed")) 
{
    case <- match.arg(case)
...
`
This makes calls with case = 'none' throw an error.

Reprex:
```r
janitor::clean_names(mtcars, case = 'none')
#> Error in match.arg(case): 'arg' should be one of "snake", "lower_camel", "upper_camel", "screaming_snake", "lower_upper", "upper_lower", "all_caps", "small_camel", "big_camel", "old_janitor", "parsed", "mixed"
```

It's a rare case but I'd like to use the clean_names functionality for removing problematic characters but not touch the case. 

I have a PR prepared if this is reasonable.

### PR DESCRIPTION
**Pull request by andrewbarros**
Fixes #269

### CODE REVIEW

**Comment by sfirke** [comment]
Looks good.  I'm not sure there's value in including "internal_parsing", it's unclear what that does and I can't see someone using it.  @Tazinho what do you think?  We could address the current state of things by omitting mention of "internal_parsing"

**Comment by sfirke** [comment]
Oh and can you try running `devtools::document()` on your branch to update the .Md documentation?  I think that is why Travis is failing.

**Comment by andrewbarros** [comment]
@sfirke I don't think there's value in internal_parsing. I've added a commit that removes references from the documentation and removes it from the list of arguments.

**Comment by sfirke** [comment]
This was great, thanks @andrewbarros !

**Pull request merged**
