### PR TITLE
clean_names() transliterates accented letters

### LINKED ISSUE #120: clean_names could transliterate accented characters
Data frames with accented characters (things like áôü) have to be wrapped with quotation in dplyr. If clean_names transliterate them to ASCII the problem would be solved.

The solution is quite simple, you would only need to add this line to the function before the duplicate handling part and also include stringi in the dependencies of the package.

`stringi::stri_trans_general(., "Latin-ASCII"))`

### PR DESCRIPTION
**Pull request by fernandovmacedo**
clean_names() transliterates accented letters. Closes #120

### CODE REVIEW

**Comment by fernandovmacedo** [comment]
I have forgotten to add the line `@importFrom stringi stri_trans_general` at the beginning of the clean_names.R file, when you merge, please add that line.

**Comment by sfirke** [comment]
Thanks for this Fernando.  I see it passes the Travis tests so must work on Linux and Mac.  I am still vexed on Windows.  (a) I think this may not work properly for Windows users until stringi 1.1.6 is on CRAN, right now https://github.com/gagolews/stringi/issues/269 is fixed only on GitHub.  And (b) the new tests work for me in the console but fail when I run `test()` - so maddening!  This is probably a personal problem but I can't figure it out.

@Tazinho what do you get for `stri_trans_general("œ", "Latin-ASCII")` on the latest stringi 1.1.6?  I installed it today from GitHub, restarted my machine, and get `"\u009c"` as my result 😭 

If this works for everyone else I'll merge it - the mode of failure isn't any worse than the original accented names so merging it before stringi 1.1.6 is out doesn't _hurt_ Windows users.

**Comment by Tazinho** [comment]
@sfirke I tested it in the last days. The stringi::stri_trans_general() works only correct for the dev version of the stringi package. So I am waiting also for the cran update of stringi (besides other things) to update the snakecase pkg on cran.

**Comment by Tazinho** [comment]
Oh, I see😂 I will test it again this evening. Currently not on my laptop...

**Comment by sfirke** [comment]
Okay, the tests passed for Mac and Linux so let's merge it.  @Tazinho, whenever you get a chance to try out the new `clean_names()` on Windows and see if it works for you on characters like œ, let us know?

Thanks @fernandovmacedo!

**Comment by fernandovmacedo** [comment]
On my windows, it works fine with the development versions of stringi and janitor.

``` r
library(stringi)
library(janitor)

tmp_df <- data.frame(a = 1, b = 2, c = 3)
names(tmp_df) <- c("€", "ação", "farœ")

tmp_df
#>   <U+0080> ação far<U+009C>
#> 1        1    2           3

df_clean <- clean_names(tmp_df)

df_clean
#>   x acao faroe
#> 1 1    2     3

stri_trans_general("farœ", "latin-ASCII")
[1] "faroe"
```

```
Session info -------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.3 (2017-03-06)
 system   x86_64, mingw32             
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  Portuguese_Brazil.1252      
 tz       America/Sao_Paulo           
 date     2017-07-13                  

Packages -----------------------------------------------------------------------------------------------------------------------------------------
 package    * version    date       source                           
 assertthat   0.2.0      2017-04-11 CRAN (R 3.3.3)                   
 backports    1.0.5      2017-01-18 CRAN (R 3.3.2)                   
 base       * 3.3.3      2017-03-06 local                            
 callr        1.0.0.9000 2017-05-18 Github (r-pkgs/callr@e23845d)    
 clipr        0.3.2      2017-01-09 CRAN (R 3.3.3)                   
 crayon       1.3.2      2016-06-28 CRAN (R 3.3.3)                   
 datasets   * 3.3.3      2017-03-06 local                            
 debugme      1.0.2      2017-03-01 CRAN (R 3.3.3)                   
 devtools   * 1.13.2     2017-06-02 CRAN (R 3.3.3)                   
 digest       0.6.12     2017-01-27 CRAN (R 3.3.3)                   
 dplyr        0.7.0      2017-06-09 CRAN (R 3.3.3)                   
 evaluate     0.10       2016-10-11 CRAN (R 3.3.3)                   
 glue         1.1.1.9000 2017-07-13 Github (tidyverse/glue@b945cd1)  
 graphics   * 3.3.3      2017-03-06 local                            
 grDevices  * 3.3.3      2017-03-06 local                            
 htmltools    0.3.5      2016-03-21 CRAN (R 3.3.3)                   
 janitor    * 0.3.0.9000 2017-07-13 Github (sfirke/janitor@13cd935)  
 knitr        1.16       2017-05-18 CRAN (R 3.3.3)                   
 magrittr     1.5        2014-11-22 CRAN (R 3.3.3)                   
 memoise      1.1.0      2017-04-21 CRAN (R 3.3.3)                   
 methods    * 3.3.3      2017-03-06 local                            
 processx     1.0.0.9000 2017-05-18 Github (r-pkgs/processx@2d0e421) 
 R6           2.2.1      2017-05-10 CRAN (R 3.3.3)                   
 Rcpp         0.12.10    2017-03-19 CRAN (R 3.3.3)                   
 reprex     * 0.1.1      2017-01-13 CRAN (R 3.3.3)                   
 rlang        0.1.1.9000 2017-07-13 Github (hadley/rlang@ff87439)    
 rmarkdown    1.3        2016-12-21 CRAN (R 3.3.3)                   
 rprojroot    1.2        2017-01-16 CRAN (R 3.3.3)                   
 stats      * 3.3.3      2017-03-06 local                            
 stringi    * 1.1.6      2017-07-13 Github (gagolews/stringi@dc94c5a)
 stringr      1.2.0      2017-02-18 CRAN (R 3.3.3)                   
 tibble       1.3.3      2017-05-28 CRAN (R 3.3.3)                   
 tools        3.3.3      2017-03-06 local                            
 utils      * 3.3.3      2017-03-06 local                            
 whisker      0.3-2      2013-04-28 CRAN (R 3.3.3)                   
 withr        1.0.2      2016-06-20 CRAN (R 3.3.3)  
```

**Comment by sfirke** [comment]
And now that works for me too!  Thanks Fernando.  Who knows what was going on... after an hour of trying to figure it out before merging, I'm just glad it works! 😌

**Pull request merged**
