### PR TITLE
Integrate snakecase-pkg into janitor

### PR DESCRIPTION
**Pull request by Tazinho**
As mentioned in #96 and #130 For the latter I changed "%" into ".percent_" instead of `"_percent_"`, as commented in the code, since starting with "_" would have been converted to "x_percent" by `make.names()` .

### CODE REVIEW

**Comment by sfirke** [comment]
Looks good.  I have two questions:

1) Test coverage: I'd like there to be tests for each of the `case` options.  Are there similar tests from `snakecase` that we could quickly incorporate?  It would be a bit repetitive but we could start by just taking the existing set of `clean_names` tests and test it under each value of case, that would be quick.

2) The part in the documentation where it notes '_There are three "special" cases available_' - do you think those will be appealing to users in this use case, automatically reformatting their variable names?  I lean toward omitting that part for brevity.

Thanks Malte!

**Comment by Tazinho** [comment]
Hi Sam,

1. There are many (more or less systematic) testcases in tests-to_any_case.R. I included your testcases for the case "snake" under the name janitor. I am currently on vacation, but afterwards will update these tests for the other cases. This should be straightforward and there should be no surprises. I wasnt sure if yould like to see the tests on my side, but I can include more tests and I'd be happy to offer support for any issues dealing with cases.

2. Hard to tell, but from a typical janitor usecase I'd expext that only snakecase, Upper/lower camel and all caps matter. Maybe parsed and mixed case also. I'd like to leave it up to you to edit the description.

Best, Malte

**Comment by Tazinho** [comment]
Testcases for all other cases are now included within 
https://github.com/Tazinho/snakecase/blob/master/tests/testthat/test-to_any_case.R

**Comment by sfirke** [comment]
Thanks for adding the additional test cases!  I'll tinker with the description per your comment above, re-read the code, hopefully this week, and then merge it.

**Comment by sfirke** [comment]
Okay if I copy those tests to janitor?  Seems like they should call `clean_names()` directly in case it changes in the future.

**Comment by Tazinho** [comment]
Definitely ok.

**Pull request merged**
