### PR TITLE
Add cutoff argument to remove_empty() (fix #446)

### LINKED ISSUE #446: Feature suggestion: function to remove columns based on missing percentage
I have some large tables that have say, 99.8 % missing.  I'm wondering if it would be useful to have a function similar to `remove_empty()` that would remove columns based on a cutoff of percent missing?

ie `remove_missing_cutoff(df, cutoff = .99)`

### PR DESCRIPTION
**Pull request by billdenney**
Add cutoff argument to remove_empty() (fix #446)

### CODE REVIEW

**Comment by sfirke** [comment]
Looks great!

Only possibility I see for improvement is in clarifying whether the cutoff is `=`, or `<=`  Say `cutoff = 0.90` -- `(rowSums(is.na(dat))/ncol(dat)) < cutoff` makes it look like a 90% empty row won't be removed, which is also what is implied in the NEWS update.  But then this in the variable description `What fraction (>0 to <=1) of rows or columns must be empty to be removed?` makes it sound like `=`.  I think it can't hurt to be as explicit as possible about whether, if cutoff = 0.9, a column that's 90% empty will be removed or not.

Thank you for adding this! 🙏

**Comment by billdenney** [comment]
Fair point that this should be explicit.  My goal is that it is consistent if we applied the same definition to `cutoff=1`.  (I'm not using the same code to prevent even a possibility of a floating point issue at `cutoff=1` since that is the common/default case.)

You're right that, with cutoff=0.9, a 90% empty column should be removed.  Fix coming momentarily...

**Comment by sfirke** [comment]
Lovely adjustment!

I'd caught that you were using different code for `cutoff == 1` but it hadn't occurred to me that it was to avoid floating point errors.  That saves what could be a very painful floating point precision error for someone 😬 

Thanks again!  Merging now.

**Comment by billdenney** [comment]
I don't know if the floating point catch is required, but it seems like a small code maintenance price to pay for ensuring that it's never a problem.

**Pull request merged**
