### PR TITLE
Additional documentation of mu/micro conversion

### PR DESCRIPTION
**Pull request by billdenney**
The issue in #448 is occurring for me a lot more.  I've added some additional documentation to assist with the conversion to "u" instead of "m".

### CODE REVIEW

**Comment by sfirke** [comment]
Looks good!  This seems kind of long:
```
replace=c("\u00b5"="u",
#' "\u03bc"="u", "\u3382"="u", "\u338c"="u", "\u338d"="u", "\u3395"="u",
#' "\u339b"="u", "\u33b2"="u", "\u33b6"="u", "\u33bc"="u")
```
Do you think it's worth writing our own shortcut for this and including it in janitor + documenting here?  E.g., the above named vector could be called `mu_to_u` and included in the package as a non-exported constant?  I could see it adding a little confusion to how _other_ replacements work, but it also would be a nice shorthand.

I don't feel strongly either way.

**Comment by billdenney** [comment]
That is a **_great_** idea!  I updated the PR.

To work around an unusual name-setting issue in R (with a question on R-package-devel), I created the constant using `setNames()` rather than directly using a named character vector.

**Review by sfirke — APPROVED** [review]
Looks great!

**Comment by sfirke** [comment]
Nice implementation, as always 🙌  This is a slick addition.  It's funny, I thought clean_names was "done" years ago.  Then it got a huge refactor for v2.0.  And stuff like this keeps making it better.

**Pull request merged**
